services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-service-h2:latest  # Define the name of the Docker image
    container_name: app-h2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test  # Use "test" or "seed" value to populate the database with sample data
